project_id = "mfsxmxbtaunnxstfcjlp"

# Edge Functions configuration
[functions.generate]
verify_jwt = true

[functions.sessions-add-message]
verify_jwt = true

[functions.storage-clear]
verify_jwt = true